words = [
    "Tirocinio",
    "adwaita",
    "bcryptjs",
    "bindable",
    "cantarell",
    "consolas",
    "crypto",
    "defval",
    "inlang",
    "klass",
    "lightningcss",
    "lucida",
    "lucide",
    "menlo",
    "noninteractive",
    "noto",
    "nums",
    "oncancel",
    "ondragleave",
    "otp",
    "paraglide",
    "segoe",
    "svelte's",
    "tippy",
    "touchmove",
    "vitest",
]
