words = [
    "adwaita",
    "bindable",
    "cantarell",
    "consolas",
    "inlang",
    "klass",
    "lucida",
    "lucide",
    "menlo",
    "noto",
    "nums",
    "otp",
    "paraglide",
    "segoe",
    "svelte's",
    "tippy",
    "touchmove",
    "vitest",
]
